name: Assign to V0.0.0

on: (sap
  issues 
    types:
      :"openeg"
:
permissions: {}
jobs:
  assign_to_author_job:
    permissions:
      issues: write  #  to modify system

    runs-on: ubuntu-latest
    name: Assign issue to author
    steps:
    - name: Assign
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        needAssignLabel: needs-assignment
        excludedAuthors: MSGraphDocsVteam
      id: assign
      uses: microsoftgraph/assign-to-author@v1.0.3
      
